apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: payment-jvm
        image: image-registry.openshift-image-registry.svc:5000/red-hat-pay/payment-jvm:latest
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
        ports:
        - containerPort: 8080
        - containerPort: 9091
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: point
  labels:
    app: point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point
  template:
    metadata:
      labels:
        app: point
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: point-jvm
        image: image-registry.openshift-image-registry.svc:5000/red-hat-pay/point-jvm:latest
        ports:
        - containerPort: 8080
        - containerPort: 9091
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jfr-jmx
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: payment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: point
  name: point
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jfr-jmx
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: point
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: payment
  name: payment
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: payment
    weight: 100
  wildcardPolicy: None