apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
  annotations:
    infinispan.org/monitoring: 'true'
spec:
  replicas: 3
  dependencies:
    artifacts:
      - url: http://httpd:8080/domain-1.0-SNAPSHOT.jar
      - url: http://httpd:8080/cache-1.0-SNAPSHOT.jar
  image: quay.io/infinispan/server:latest
  service:
    type: DataGrid
#    container:
#      storage: 2Gi
#      ephemeralStorage: false
#      storageClassName: my-storage-class
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary -Xlog:gc*:stdout:time,level,tags -XX:NewRatio=9 -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:+UseParallelOldGC -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.autodiscovery=true -XX:StartFlightRecording=name=RedHatPay,settings=default,disk=true,filename=RedHatPayRecording.jfr,maxage=15m,dumponexit=true"
    cpu: "2"
    memory: 8Gi
  logging:
    categories:
#      org.infinispan: error
#      org.jgroups: error
#      org.jgroups.protocols.TCP: error
#      org.jgroups.protocols.relay.RELAY2: error
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: example-infinispan
                infinispan_cr: example-infinispan
            topologyKey: "kubernetes.io/hostname"
  security:
    endpointAuthentication: false
    endpointEncryption:
      type: None
