apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: put-schema
spec:
  cluster: example-infinispan
  config: |
    echo "creating schema..."
    schema --upload=../../cache/target/classes/proto/PaymentSchema.proto PaymentSchema.proto
    schema --upload=../../cache/target/classes/proto/PointSchema.proto PointSchema.proto
    echo "list Protobuf schema"
    ls schemas