apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
  annotations:
    infinispan.org/monitoring: 'true'
spec:
  replicas: 2
  dependencies:
    artifacts:
      - url: http://web-test/domain-1.0-SNAPSHOT.jar
        hash: md5:0d7c7f5c1b3bd1c88e519800ecfa6a0a
      - url: http://web-test/cache-1.0-SNAPSHOT.jar
        hash: md5:cfff036fa4403b0112930940985e4c7a
  image: quay.io/infinispan/server:latest
  service:
    type: DataGrid
#    container:
#      storage: 2Gi
#      ephemeralStorage: false
#      storageClassName: my-storage-class
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary -Xlog:gc*:stdout:time,level,tags"
    cpu: "1000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: error
      org.jgroups: error
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: example-infinispan
                infinispan_cr: example-infinispan
            topologyKey: "kubernetes.io/hostname"
