apiVersion: v1
kind: Pod
metadata:
  name: datagrid-libs-nginx
  labels:
    app: web
    env: test
spec:
  containers:
    - name: nginx
      image: nginx:1.17.2-alpine
      volumeMounts:
        - name: lib-pv-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: lib-pv-storage
      persistentVolumeClaim:
        claimName: datagrid-libs
---
apiVersion: v1
kind: Service
metadata:
  name: web-test
spec:
  type: NodePort
  selector:
    app: web
    env: test
  ports:
    - port: 80
      nodePort: 30000