apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: mybatch
spec:
  cluster: example-infinispan
  config: |
    echo "creating schema..."
    schema --upload=proto/payment.proto payment.proto
    schema --upload=proto/point.proto point.proto
    echo "list Protobuf schema"
    ls schemas