apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-node-custom
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - data: |
        [main]
        summary=Custom OpenShift node profile with an additional kernel parameter
        include=openshift-node
        [sysctl]
        net.core.rmem_max=16777216
        net.core.wmem_max=16777216
        net.ipv4.tcp_mem="65536 131072 262144"
        net.ipv4.tcp_rmem="262144 4194304 8388608"
        net.ipv4.tcp_wmem="65536 1048576 2097152"
        vm.swappiness=0
      name: openshift-node-custom
  recommend:
    - machineConfigLabels:
        machineconfiguration.openshift.io/role: "worker"
      priority: 20
      profile: openshift-node-custom